name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/python-hello-world .

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/python-hello-world

  deployment:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH Key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << EOF
        docker pull ${{ secrets.DOCKER_USERNAME }}/python-hello-world
        docker stop python-container || true
        docker rm python-container || true
        docker run -d -p 80:5000 --name python-container ${{ secrets.DOCKER_USERNAME }}/python-hello-world
        EOF
